# Generated by Django 4.2.5 on 2023-10-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
